### ISSUE TITLE
Missing Psr\EventDispatcher\EventInterface ?

### ISSUE THREAD

**Issue by harikt** [Crell/Tukio#5]
Hi @Crell ,

I have been looking at the event-dispatcher.

Missing `Psr\EventDispatcher\EventInterface`  at  https://github.com/php-fig/event-dispatcher/tree/8380006c4192e22528ce40c3a56b81590707128a/src

But the interface is used in many places. Eg :  https://github.com/php-fig/event-dispatcher-util/blob/8bb440229e615a06a5e85e1cdf8e3c99abaa0a53/src/AggregateProvider.php#L7

The interface is mentioned at  https://github.com/php-fig/fig-standards/blob/d8693cde3fae95ae3127649fe5482384e819e0e0/proposed/event-dispatcher.md#interfaces

**Comment by Crell** [comment]
We just recently removed `EventInterface` from the spec.  There's an outstanding PR to update the spec text itself: https://github.com/php-fig/fig-standards/pull/1128.

The base package, the util package, and Tukio have already been updated to the latest version, so they technically lead the text; the PR there is the latest definitive version at the moment.

If there's any stray `use` statements for `EventInterface` still lying around, that's just a refactoring bug that we can/should clean up.
